### ISSUE TITLE
Squeezing performance

### ISSUE THREAD

**Issue by hasenj** [tris-foundation/messagepack#2]
I'm not sure if this is the appropriate place for this question, but I noticed that I can improve performance by about 30% if I call the encoder directly instead of preparing a `MessagePack` structure.

Currently the `writeArrayHeader` and `writeMapHeader` are internal so they are not usable. However in a local project I changed them to public to test the following scenario:

Say I have a struct:

```
struct ComplicatedThing {
    let id: Int = 10
    let message: String = "hello"
}
```

And I want to be able to message pack it, so I supply a `pack` method that produces a MessagePack dictionary:

```
    func pack() -> MessagePack {
        return MessagePack([
            MessagePack("id"): MessagePack(self.id),
            MessagePack("message"): MessagePack(self.message),
        ])
    }
```

Now suppose I have an array of 50000 instances and I want to convert encode the entire array.

```
let count = 50000
var arr: [ComplicatedThing] = []
for i in 0..<count {
    arr.append(ComplicatedThing())
}
```

I want to time the encoding process so first some quick helpers:

```
func ms(since t: Date) -> Double {
    return Date().timeIntervalSince(t) * 1000
}

func msSince(_ t: Date) -> String {
    return String(format: "%.2fms", ms(since: t))
}
```

Now this is how I timed the packing and encoding process:

```
let tpack = Date()
let arrpack = MessagePack(arr.map { s in s.pack() })
print("Packing: \(msSince(tpack))")
let tenc = Date()
let bytes = MessagePack.encode(arrpack)
print("Encoding: \(msSince(tenc))")
print("Total: \(msSince(tpack))")
```

I consider two steps to encode, first prepare a MessagePack object, then encode it.

I built the project in release mode with optimizations:

     $  swift build --configuration release -Xswiftc -O

And the time reported varies obviously but it hovers around:

```
Packing: 22.46ms
Encoding: 34.63ms
Total: 57.59ms
```
Now I thought about ways to make this faster, and I figured I could call the lower level functions directly:

```
var enc = Encoder()
let tlow = Date()
enc.writeArrayHeader(count: arr.count)
for item in arr {
    enc.writeMapHeader(count: 2)
    enc.encode("id")
    enc.encode(item.id)
    enc.encode("message")
    enc.encode(item.message)
}
print("Low Level Encoding: \(msSince(tlow))")
```

The time it took is:

```
Low Level Encoding: 39.24ms
```

I also compared the bytes output to make sure it's the same, and it seems to be the same.

My analysis is that it takes the same time as the "encoding" step from the official supported method.

The encoding itself is not really any faster. We're just skipping the "preparation" step, that's why overall we're spending less time.

This might seem like pulling hairs but I have an actual real life use case where I'm trying to switch a part of a web app from Python to Swift, and while I am indeed gaining significant performance improvement, there's a bottle neck in the final step of writing the response. It seems to be spending about 30ms (per request) to just write the response (it's a huge list), however, much that of that time (around 25ms) is just just spent to _prepare_ the MessagePack objects (in the same way as the above example).

I understand that exposing `writeArrayHeader` and `writeMapHeader` is probably out of the question. But if so what other possibilities are there for allowing quicker encoding without allowing the user to shoot themselves in the foot.

**Comment by tonyfreeman** [comment]
Sorry for the delay. Yeah, i see the issue. I'm not sure if we can do something about it for Swift 3 without exposing writeHeader because iirc using `Any` and checking the real type was significantly  slower. Perhaps Swift 4 with Codable protocols can help with this. I'll look into it, thank you!

**Comment by tonyfreeman** [comment]
We can add `encode<T>(_ values: [T] or even [Any])` to avoid exposing writeArrayHeader but the real problem is Map, because in any way it causes construction of an extra object (`Dictionary<...>` or `(key: String, value: Any)` or some kind of functional _encoders_) which is slow by itself.
Using your example, 50k dictionary objects took about 16ms 
```swift
@inline(never)
func blackHole<T>(_ value: T) {}

let tdict = Date()
for item in arr {
    blackHole(["id": item.id, "message": item.message])
}
print("Dict: \(msSince(tdict))")
```
the whole idea of this Encoders is to provide high-performance low-level api, so i don't see any reason why we can't make it public. It may cause shooting in the foot, but it's not much different form some kind of "Index out of range" errors and we don't really have much choice right now, it's always about convenience vs performance. I'll try Swift 4 Codable a bit later, but anyway it will be slower than writing directly into an array.

**Comment by tonyfreeman** [comment]
closed by https://github.com/tris-foundation/messagepack/commit/15378ecb9cdbaa49a5045473ab38e74e91a3adff

**Comment by hasenj** [comment]
Thanks for your response!

I'm not sure about what Swift features can help. I think ideally an object could have is own 'encode' method that takes an encoder and write to it, and ideally this encode method should be generated or 'meta programmed' at compile time (so as to not incur runtime costs).

But for now this should more than suffice! Thanks again!
