### ISSUE TITLE
Xcode won't build - 'UnsafeMutableRawPointer' has no member 'copyMemory'

### ISSUE THREAD

**Issue by wildthink** [tris-foundation/messagepack#9]
When using a generated Xcode project the following error appears many times.

Value of type 'UnsafeMutableRawPointer' has no member 'copyMemory'

This fails on the master and 4.0 branch.

**Comment by tonyfreeman** [comment]
Hi, please make sure you did `swift package reset` after you switch branches.
I've just tested 4.0 branch with Xcode Version 9.2 (9C40b), I don't have this errors

**Comment by tonyfreeman** [comment]
All of our modules were branched just before the upgrade, If you would like to use the latest(master) branch please download a newer swift 4.1 dev snapshot.

**Comment by tonyfreeman** [comment]
You you still have this error feel free to reopen the issue!

**Comment by tonyfreeman** [comment]
> please make sure you did swift package reset after you switch branches

btw most of the time `swift package update`, `swift package generate-xcodeproj` is enough.

**Comment by wildthink** [comment]
Thanks! The `swift package update` did the trick. 👍
